/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package eletrotech.gui;

import eletrotech.api.API;
import eletrotech.api.Employee;
import static eletrotech.gui.Home.showCard;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Arthur
 */
public class EmployeeForm extends javax.swing.JPanel {
    
    public EmployeeForm() throws IOException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        passField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        roleSelect = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(900, 472));
        setPreferredSize(new java.awt.Dimension(900, 472));

        listPanel.setBackground(java.awt.Color.white);
        listPanel.setMaximumSize(new java.awt.Dimension(925, 32767));

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setMaximumSize(new java.awt.Dimension(1000, 80));
        jPanel2.setMinimumSize(new java.awt.Dimension(1000, 80));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 80));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(40, 40, 40));
        titleLabel.setText("Cadastrar funcionário");
        jPanel2.add(titleLabel);

        listPanel.add(jPanel2);

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setMaximumSize(new java.awt.Dimension(1000, 45));
        jPanel3.setMinimumSize(new java.awt.Dimension(1000, 45));
        jPanel3.setName(""); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 45));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 40, 40));
        jLabel2.setText("Nome: ");
        jLabel2.setMaximumSize(new java.awt.Dimension(66, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(66, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(66, 20));
        jPanel3.add(jLabel2);

        nameField.setBackground(new java.awt.Color(234, 234, 234));
        nameField.setForeground(new java.awt.Color(51, 51, 51));
        nameField.setMinimumSize(new java.awt.Dimension(200, 22));
        nameField.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel3.add(nameField);

        listPanel.add(jPanel3);

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setMaximumSize(new java.awt.Dimension(1000, 45));
        jPanel4.setMinimumSize(new java.awt.Dimension(1000, 45));
        jPanel4.setName(""); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 45));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 40, 40));
        jLabel4.setText("E-mail:");
        jLabel4.setMaximumSize(new java.awt.Dimension(66, 20));
        jLabel4.setMinimumSize(new java.awt.Dimension(66, 20));
        jLabel4.setPreferredSize(new java.awt.Dimension(66, 20));
        jPanel4.add(jLabel4);

        emailField.setBackground(new java.awt.Color(234, 234, 234));
        emailField.setForeground(new java.awt.Color(51, 51, 51));
        emailField.setMinimumSize(new java.awt.Dimension(200, 22));
        emailField.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel4.add(emailField);

        listPanel.add(jPanel4);

        jPanel7.setBackground(java.awt.Color.white);
        jPanel7.setMaximumSize(new java.awt.Dimension(1000, 45));
        jPanel7.setMinimumSize(new java.awt.Dimension(1000, 45));
        jPanel7.setName(""); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(1000, 45));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(40, 40, 40));
        jLabel5.setText("Senha:");
        jLabel5.setMaximumSize(new java.awt.Dimension(66, 20));
        jLabel5.setMinimumSize(new java.awt.Dimension(66, 20));
        jLabel5.setPreferredSize(new java.awt.Dimension(66, 20));
        jPanel7.add(jLabel5);

        passField.setBackground(new java.awt.Color(234, 234, 234));
        passField.setForeground(new java.awt.Color(51, 51, 51));
        passField.setMinimumSize(new java.awt.Dimension(200, 22));
        passField.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel7.add(passField);

        listPanel.add(jPanel7);

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setMaximumSize(new java.awt.Dimension(1000, 45));
        jPanel5.setMinimumSize(new java.awt.Dimension(1000, 45));
        jPanel5.setName(""); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(1000, 45));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(40, 40, 40));
        jLabel6.setText("Endereço:");
        jPanel5.add(jLabel6);

        addressField.setBackground(new java.awt.Color(234, 234, 234));
        addressField.setForeground(new java.awt.Color(51, 51, 51));
        addressField.setMinimumSize(new java.awt.Dimension(200, 22));
        addressField.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel5.add(addressField);

        listPanel.add(jPanel5);

        jPanel6.setBackground(java.awt.Color.white);
        jPanel6.setMaximumSize(new java.awt.Dimension(1000, 45));
        jPanel6.setMinimumSize(new java.awt.Dimension(1000, 45));
        jPanel6.setName(""); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(1000, 45));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(40, 40, 40));
        jLabel8.setText("Cargo:");
        jLabel8.setMaximumSize(new java.awt.Dimension(66, 20));
        jLabel8.setMinimumSize(new java.awt.Dimension(66, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(66, 20));
        jPanel6.add(jLabel8);

        roleSelect.setBackground(new java.awt.Color(234, 234, 234));
        roleSelect.setForeground(new java.awt.Color(51, 51, 51));
        roleSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Técnico" }));
        roleSelect.setFocusable(false);
        roleSelect.setMinimumSize(new java.awt.Dimension(200, 22));
        roleSelect.setPreferredSize(new java.awt.Dimension(200, 22));
        roleSelect.setRequestFocusEnabled(false);
        roleSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleSelectActionPerformed(evt);
            }
        });
        jPanel6.add(roleSelect);

        listPanel.add(jPanel6);

        jPanel10.setBackground(java.awt.Color.white);
        jPanel10.setMaximumSize(new java.awt.Dimension(1000, 45));
        jPanel10.setMinimumSize(new java.awt.Dimension(1000, 45));
        jPanel10.setName(""); // NOI18N
        jPanel10.setPreferredSize(new java.awt.Dimension(1000, 45));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jButton2.setBackground(new java.awt.Color(255, 98, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("CADASTRAR");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 98, 0), 2, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(200, 35));
        jButton2.setMinimumSize(new java.awt.Dimension(200, 35));
        jButton2.setPreferredSize(new java.awt.Dimension(200, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton2);

        status.setBackground(new java.awt.Color(0, 153, 51));
        status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(0, 102, 51));
        jPanel10.add(status);

        listPanel.add(jPanel10);

        jPanel11.setBackground(java.awt.Color.white);
        jPanel11.setMaximumSize(new java.awt.Dimension(1000, 45));
        jPanel11.setMinimumSize(new java.awt.Dimension(1000, 45));
        jPanel11.setName(""); // NOI18N
        jPanel11.setPreferredSize(new java.awt.Dimension(1000, 45));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jButton3.setBackground(new java.awt.Color(255, 98, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 98, 0), 2, true));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setLabel("VOLTAR");
        jButton3.setMaximumSize(new java.awt.Dimension(200, 35));
        jButton3.setMinimumSize(new java.awt.Dimension(200, 35));
        jButton3.setPreferredSize(new java.awt.Dimension(200, 35));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton3);

        listPanel.add(jPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            showCard("Employees", new Employees());
        } catch (IOException ex) {
            Logger.getLogger(EmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void roleSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleSelectActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Employee employee = new Employee();
        
        employee.setUsername(nameField.getText());
        employee.setEmail(emailField.getText());
        employee.setAddress(addressField.getText());
        employee.setPassword(passField.getText());
        String role = roleSelect.getSelectedItem().toString().equals("Técnico") ? "technician" : "admin"; 
        employee.setRole(role);
        
        try {
            if(API.createEmployee(employee)) {
                showCard("Employees", new Employees());
            }
        } catch (IOException ex) {
            Logger.getLogger(EmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel listPanel;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField passField;
    private javax.swing.JComboBox<String> roleSelect;
    private javax.swing.JLabel status;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
